apiVersion: apps/v1
kind: Deployment
metadata:
  name: lectify-backend
  labels:
    app: lectify
    use: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lectify
      use: backend
  strategy: 
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
  template:
    metadata:
      labels:
        app: lectify
        use: backend
    spec:
      containers:
        - name: lectify-backend
          image: lectifycr.azurecr.io/lectify-backend:72a2e51fc19369ef5e485a0ceeddd67f203ee932
          ports:
            - containerPort: 5000
          securityContext:
            runAsUser: 1000
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          readinessProbe:
            exec:
              command:
              - ls
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: openapi-key
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongo-connection-string

---

apiVersion: v1
kind: Service
metadata:
  name: lectify-backend-service
spec:
  selector:
    app: lectify
    use: backend
  ports:
    - port: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  openapi-key: changeme
  mongo-connection-string: changeme
